### ISSUE TITLE
rawset* routines raise merr

### ISSUE THREAD

**Issue by starwing** [Oberon00/Oberon00.github.io#2]
as title.

**Comment by Oberon00** [comment]
Thank you for the hint, I fixed it & also fixed the error category for the loadfile* routines and added a link to the gist from which that table is generated.

Cool to see that someone is still using this table. May I ask how you have come to find it?

**Comment by starwing** [comment]
I find it from lua-l, and added it to my bookmark and used to check error condition when writing bindings in C and other languages. (for aware which interface may raise error :-(
